[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "ExtendedMenus"
versionNumber = "${PACKAGE_VERSION}"
description = "Extends Menus"
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/master/ExtendedMenus"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.19"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"

[[build.copy]]
source = "bin"
target = "files/plugins/"

[[build.copy]]
source = "../Assets/assets"
target = "files/plugins/assets"

[publish]
repository = "https://outward.thunderstore.io"