[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "Transmorph"
versionNumber = "${PACKAGE_VERSION}"
description = "Change the appearance of Weapons and Armor through the new Transmogrify crafting menu."
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/mods/transmorph"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.15"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"

[[build.copy]]
source = "bin"
target = "files/plugins/"

[[build.copy]]
source = "../Assets/assets"
target = "files/plugins/assets"

[publish]
repository = "https://outward.thunderstore.io"