[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "RespecPotions"
versionNumber = "${PACKAGE_VERSION}"
description = "Respec Potions"
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/mods/respec-potions/RespecPotions"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.15"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"

[[build.copy]]
source = "bin"
target = "files/plugins/"

[[build.copy]]
source = "../Assets/icons"
target = "files/plugins/icons"

[publish]
repository = "https://outward.thunderstore.io"