// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._alchemyCraftingBg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._allRecipes")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._availableIngredients")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._complexeRecipes")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._cookingFireCraftingBg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._cookingPotCraftingBg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._craftingStation")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._currentlyDisplayedCraftingType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._freeRecipeDescriptionPanel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._freeRecipeDisplay")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._freeRecipesLocKey")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._imgCraftingBackground")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._ingredientSelectorCachedItems")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._ingredientSelectors")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._ingredientSelectorTemplate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._itemDetailPanel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._lastFreeRecipeIndex")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._lastFreeRecipeIngredientIDs")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._lastRecipeIndex")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._lblFreeRecipeDescription")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._lblStationName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._multipleIngrenentsBrackground")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._recipeDisplays")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._recipeDisplayTemplate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._recipeResultDisplay")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._recipeSeparator")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._refreshComplexeRecipeRequired")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._selectorWindowPos")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._simpleMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._singleIngredientBackground")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._survivalCraftingBg")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.CustomCraftingMenu._tempSelectorWindow")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ModifAmorphic.Outward.Modules.Crafting.Services.CustomRecipeService._recipeManager")]
