[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "HallowedMarshFoilagePack"
versionNumber = "${PACKAGE_VERSION}"
description = "Makes tree blueprints from the Caldera region available for purchase and construction in New Sirocco."
websiteUrl = "https://github.com/ModifAmorphic/outward/wiki/NewCaldera"
containsNsfwContent = false

[package.dependencies]
ModifAmorphic-NewCaldera = "1.0.0"

[build]
icon = "Assets/icon.png"
readme = "../README.md"
outdir = "Build"

[[build.copy]]
source = "../buildingsManifest.json"
target = "files/plugins/"

[[build.copy]]
source = "../asset-bundles"
target = "files/plugins/asset-bundles"

[[build.copy]]
source = "../Locales"
target = "files/plugins/Locales"

[publish]
repository = "https://outward.thunderstore.io"
communities = ["Outward"]
categories = ["Items", "Misc"]