[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "StashPacks"
versionNumber = "${PACKAGE_VERSION}"
description = "Access your stash from any game, anywhere!"
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/mods/stash-packs/StashPacks"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.8"
Mefino-Outward_Config_Manager = "16.3.3"
sinai-dev-SideLoader = "3.4.10"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"


[[build.copy]]
source = "bin"
target = ""

[publish]
repository = "https://outward.thunderstore.io"