[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "Transmorphic"
versionNumber = "${PACKAGE_VERSION}"
description = "Transmogrify your equipment with a new crafting system. Support for Weapons, Armor, Backpacks, Lanterns and Lexicons. Plus balanced Alchemy and Cooking Menus."
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/master/Transmorphic"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.15"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"

[[build.copy]]
source = "bin"
target = "files/plugins/"

[[build.copy]]
source = "../Assets/assets"
target = "files/plugins/assets"

[publish]
repository = "https://outward.thunderstore.io"