[config]
schemaVersion = "0.0.1"

[package]
namespace = "ModifAmorphic"
name = "Extra_QuickSlots"
versionNumber = "${PACKAGE_VERSION}"
description = "Adds Extra QuickSlots to the Keyboard Quickslot Bar"
websiteUrl = "https://github.com/ModifAmorphic/outward/tree/master/ExtraSlots"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Outward = "5.4.15"
sinai-dev-SideLoader = "3.5.0"

[build]
icon = "Assets/icon.png"
readme = "Assets/README.md"
outdir = "Build"


[[build.copy]]
source = "bin"
target = ""

[publish]
repository = "https://outward.thunderstore.io"