# This is a basic workflow to help you get started with Actions

name: outward-shared-release-version-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - 'Outward.Shared/*'
    paths-ignore:
    - '**/README.md'
    - '**/readme.md'
    - '**/workflows/*'
    - '**/manifest.json'
    - '**/icon.png'
    
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ModifAmorphic/outward
            azure-pipeline-name: 'release-outward-shared-build'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
