name: outward-shared-develop-CI

# Controls when the workflow will run
on:
  push:
    branches: [ outward-shared ]
    paths:
    - 'Outward.Shared/**'
    - '!**/README.md'
    - '!**/readme.md'
    - '!**/workflows/*'
    - '!**/manifest.json'
    - '!**/icon.png'
  pull_request:
    branches: [ outward-shared ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Run Outward-Shared Next-Version Azure Build Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Run Build outward-shared-next-version-build
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ModifAmorphic/outward
            azure-pipeline-name: 'outward-shared-develop-build'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
